#!/bin/sh /etc/rc.common

START=50

load_iolines_boot() {	

	config_get dev "$1" "dev"
	
	num=$(echo ${dev:7:1})
	pu="/dev/pu$num"
	pd="/dev/pd$num"
	
	config_get mode "$1" "mode"
	config_get enabled "$1" "enabled" "0"
	if [ $enabled -eq 1 ]; then
		case "$mode" in
			"mode1")
				echo in > $pu/direction
				echo low > $pd/direction
				;;
			"mode2")
				echo low > $pu/direction
				echo low > $pd/direction
				;;
			"mode3")
				echo high > $pu/direction
				echo high > $pd/direction
				;;
		esac		
	fi
}

load_iolines() {	

	config_get dev "$1" "dev"
	
	num=$(echo ${dev:7:1})
	pu="/dev/pu$num"
	pd="/dev/pd$num"
	
	config_get mode "$1" "mode"
		
	case "$mode" in
		"mode1")
			echo in > $pu/direction
			echo low > $pd/direction
			;;
		"mode2")
			echo low > $pu/direction
			echo low > $pd/direction
			;;
		"mode3")
			echo high > $pu/direction
			echo high > $pd/direction
			;;
	esac		

}

boot() {
	config_load iolines
	config_foreach load_iolines_boot io
}

restart() {
	config_load iolines
	config_foreach load_iolines io
}
