# Custom configurator
#
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pollmydevice
LUCI_DEPENDS:= +pollmydevice

# Version: <major>.<minor>.<patch>
PKG_VERSION:=0.7

PKG_RELEASE:=1

LUCI_TITLE:=LuCI TCP to RS232 and RS485 Configuration Frontend

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
