# Custom configurator
#
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-report
LUCI_DEPENDS:=

# Version: <major>.<minor>.<patch>
PKG_VERSION:=0.1.0

PKG_RELEASE:=1

LUCI_TITLE:=LuCI utility to collect debug information

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
