# Custom configurator
#
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-iolines
LUCI_DEPENDS:=

# Version: <major>.<minor>.<patch>
PKG_VERSION:=0.2.0

PKG_RELEASE:=2

LUCI_TITLE:=LuCI I/O switcher

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
