#!/bin/sh /etc/rc.common

START=12
USE_PROCD=1

start_service()
{
	procd_open_instance	
	/etc/initscripts/iolines &
	/etc/initscripts/modeminit &
	/etc/initscripts/usbhost &
	/etc/initscripts/rtcinit &
	/etc/initscripts/gpsinit &
	/etc/initscripts/upgrade &
	procd_close_instance
}
