#!/bin/sh /etc/rc.common

START=12
STOP=84

start()
{
	/etc/initscripts/symlinks &
	/etc/initscripts/modeminit &
	/etc/initscripts/usbhost &
	/etc/initscripts/gpsinit &
	/etc/initscripts/upgrade &	
	/etc/initscripts/rtcinit
}
