#!/bin/sh

echo high > /sys/class/gpio/gpio61/direction
sleep 0.3
echo low > /sys/class/gpio/gpio61/direction
sleep 0.1
echo high > /sys/class/gpio/gpio61/direction
sleep 0.3
echo low > /sys/class/gpio/gpio61/direction

exit 0