#!/bin/sh

#echo "ACTION: $ACTION, SUBSYSTEM: $SUBSYSTEM, DEVTYPE: $DEVTYPE, DEVICENAME: $DEVICENAME" >> /tmp/foo.log

[ "$DEVTYPE" = "partition" -a "$ACTION" = "add" ] && {
    echo "$DEVICENAME" | grep 'mmcblk' || exit 0
    uptime=$(cat /proc/uptime)
    uptime=${uptime%%.*}
    [ "$uptime" -gt "20" ] || sleep 30
    test -d /mnt/$DEVICENAME || mkdir /mnt/$DEVICENAME
    mount -o rw /dev/$DEVICENAME /mnt/$DEVICENAME
    UPGR_FILE=$(ls -1 /mnt/$DEVICENAME/Upgrade_v* | tail -n1)
    if [ -n "$UPGR_FILE" ]; then
        logger "Sysupgrade file found"
        cp $UPGR_FILE /tmp/sysupgrade_gtr.tar
        logger "Sysupgrade process started"
        fw_setenv update_flag 113
        sysupgrade -t && sysupgrade -u || logger "Sysupgrade process cancelled"
    fi
}

[ "$DEVTYPE" = "partition" -a "$ACTION" = "remove" ] && {
    echo "$DEVICENAME" | grep 'mmcblk' || exit 0
    umount /mnt/$DEVICENAME
    sleep 1
    rmdir /mnt/$DEVICENAME/
}
