#!/bin/sh

#echo "ACTION: $ACTION, SUBSYSTEM: $SUBSYSTEM, DEVTYPE: $DEVTYPE, DEVICENAME: $DEVICENAME" >> /tmp/foo.log

[ "$DEVTYPE" = "partition" -a "$ACTION" = "add" ] && {
    echo "$DEVICENAME" | grep 'sd[a-z][1-9]' || exit 0
    test -d /mnt/$DEVICENAME || mkdir /mnt/$DEVICENAME
    mount /dev/$DEVICENAME /mnt/$DEVICENAME
}

[ "$DEVTYPE" = "partition" -a "$ACTION" = "remove" ] && {
    echo "$DEVICENAME" | grep 'sd[a-z][1-9]' || exit 0
    umount /mnt/$DEVICENAME
    sleep 1
    rmdir /mnt/$DEVICENAME/
}
