# Custom configurator
#
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-gpioswitch
LUCI_DEPENDS:=

# Version: <major>.<minor>.<patch>
PKG_VERSION:=0.1.0

PKG_RELEASE:=2

LUCI_TITLE:=LuCI GPIO switcher

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
